orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: .
          api-key-variable: 8fb16fda-fcab-45a5-a274-f4fe86005f7b:aSmQZ+cI7sJi2QQCKjlALhMbtyI= 
          prisma-api-url: https://api.eu.prismacloud.io